name: CI

on:
  workflow_call:
    secrets:
      charmhub-token:
        required: true

jobs:
  lib-check:
    name: Check libraries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check libs
        uses: canonical/charming-actions/check-libraries@1.0.3
        with:
          credentials: "${{ secrets.charmhub-token }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: python3 -m pip install tox
      - name: Run linters
        run: tox -e lint
  unit-test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: python3 -m pip install tox
      - name: Run tests
        run: tox -e unit
  build-indico-image:
    name: Build indico image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build indico image
        uses: docker/build-push-action@v2
        with:
          tags: 127.0.0.1:32000/indico:latest
          file: indico.Dockerfile
          outputs: type=docker,dest=/tmp/indico.tar
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: indico
          path: /tmp/indico.tar
  build-nginx-image:
    name: Build nginx image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build indico image
        uses: docker/build-push-action@v2
        with:
          tags: 127.0.0.1:32000/indico-nginx:latest
          file: indico-nginx.Dockerfile
          outputs: type=docker,dest=/tmp/indico-nginx.tar
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: indico-nginx
          path: /tmp/indico-nginx.tar
  integration-test-microk8s:
    name: Integration tests (microk8s)
    runs-on: ubuntu-latest
    needs: [build-indico-image, build-nginx-image]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          provider: microk8s
      - name: Enable microk8s registry
        run: sudo microk8s.enable registry
      - name: Download indico image
        uses: actions/download-artifact@v2
        with:
          name: indico
          path: /tmp
      - name: Download nginx image
        uses: actions/download-artifact@v2
        with:
          name: indico-nginx
          path: /tmp
      - name: Push images to microk8s registry
        run: |
          docker load --input /tmp/indico.tar
          docker load --input /tmp/indico-nginx.tar
          docker image ls
          docker push localhost:32000/indico:latest
          docker push localhost:32000/indico-nginx:latest
          microk8s ctr images ls
      - name: Run integration tests
        run: tox -e integration -- --model testing --indico-image localhost:32000/indico:latest --indico-nginx-image localhost:32000/indico-nginx:latest
      - name: Dump logs
        uses: canonical/charm-logdump-action@main
        if: failure()
        with:
          app: indico
          model: testing
