name: CI

on:
  workflow_call:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: python3 -m pip install tox
      - name: Run linters
        run: tox -e lint
  unit-test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: python3 -m pip install tox
      - name: Run tests
        run: tox -e unit
  build-indico-image:
    name: Build indico image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx
      - name: Build image
        uses: docker/build-push-action@v2
        with:
          tags: localhost:32000/indico:latest
          file: indico.Dockerfile
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max
          outputs: type=oci,dest=/tmp/indico.tar
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: indico
          path: /tmp/indico.tar
  build-nginx-image:
    name: Build nginx image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx
      - name: Build image
        uses: docker/build-push-action@v2
        with:
          tags: localhost:32000/indico-nginx:latest
          file: indico-nginx.Dockerfile
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max
          outputs: type=oci,dest=/tmp/indico-nginx.tar
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: indico-nginx
          path: /tmp/indico-nginx.tar
  integration-test-microk8s:
    name: Integration tests (microk8s)
    runs-on: ubuntu-latest
    needs: [build-indico-image, build-nginx-image]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          provider: microk8s
      - name: Enable microk8s registry
        run: sudo microk8s.enable registry
      - name: Download all artifacts
        uses: actions/download-artifact@v3
      - name: Push indico image to microk8s registry
        run: |
          docker load --input indico/indico.tar
          docker push localhost:32000/indico:latest
      - name: Push nginx image to microk8s registry
        run: |
          docker load --input indico-nginx/indico-nginx.tar
          docker push localhost:32000/indico-nginx:latest
      - name: Run integration tests
        run: tox -e integration -- --model testing --indico-image localhost:32000/indico:latest --indico-nginx-image localhost:32000/indico-nginx:latest
      - name: Dump logs
        uses: canonical/charm-logdump-action@main
        if: failure()
        with:
          app: indico
          model: testing
